Add stress-etcd
kyma-incubator/service-catalog-tester pull request #5
Opened 2018-12-07 10:33 UTC by adamwalach

This PR was created as part of the https://github.com/kyma-project/kyma/issues/1802

2018-12-10 10:38 UTC, klaudiagrz commented on tools/stress-etcd/README.md
> +## About
```suggestion
# Stress-etcd
```

2018-12-10 10:38 UTC, klaudiagrz commented on tools/stress-etcd/README.md
> +## About
Please add the overview section below the title:
`## Overview`

2018-12-10 10:38 UTC, klaudiagrz commented on tools/stress-etcd/README.md
> +stress-etcd populates keys in etcd database. It can be used as a simple tool
```suggestion
Stress-etcd is a tool that populates keys in the etcd database. You can use it
```

2018-12-10 10:38 UTC, klaudiagrz commented on tools/stress-etcd/README.md
> +to evaluate performance of an etcd cluster
```suggestion
to evaluate the performance of an etcd cluster.
```

2018-12-10 10:38 UTC, klaudiagrz commented on tools/stress-etcd/README.md
> +>**NOTE:** In version 0.5.0 of Kyma there was a change in naming convention of the etcd cluster.
```suggestion
>**NOTE:** Naming convention of the etcd cluster changed in Kyma version 0.5.0.
```

2018-12-10 10:38 UTC, klaudiagrz commented on tools/stress-etcd/README.md
> +to test the older version please modify content of get-ssl-files.sh script and the port-forward command.
```suggestion
to test the older version, modify the content of the `get-ssl-files.sh` script and the port-forward command.
```

2018-12-10 10:38 UTC, klaudiagrz commented on tools/stress-etcd/README.md
> +### Quick version
Remove the heading.

2018-12-10 10:38 UTC, klaudiagrz commented on tools/stress-etcd/README.md
> +### Full version
Remove the heading.

2018-12-10 10:38 UTC, klaudiagrz commented on tools/stress-etcd/README.md
> +To run the test you have to perform following steps:
```suggestion
Follow these steps to run the test:
```

2018-12-10 10:38 UTC, klaudiagrz commented on tools/stress-etcd/README.md
> +To test performance of an etcd cluster you first need to establish a connection.
Remove this sentence.

2018-12-10 10:38 UTC, klaudiagrz commented on tools/stress-etcd/README.md
> +To connect to etcd instance running on K8S cluster you have to forward a port from
```suggestion
To connect to the etcd instance running on Kubernetes cluster, forward a port from 
```

2018-12-10 10:38 UTC, klaudiagrz commented on tools/stress-etcd/README.md
> +one of etcd instances.
```suggestion
one of the etcd instances. 
```

2018-12-10 10:38 UTC, klaudiagrz commented on tools/stress-etcd/README.md
> +This command opens port `2379` on localhost:
```suggestion
Run this command to open the `2379` port on localhost: 
```

2018-12-10 10:38 UTC, klaudiagrz commented on tools/stress-etcd/README.md
> +
Please move the paragraph above under the point no.1.

2018-12-10 10:38 UTC, klaudiagrz commented on tools/stress-etcd/README.md
> +To download certificates from etcd instance execute `get-ssl-files.sh` script.
```suggestion
To download certificates from the etcd instance, run the `get-ssl-files.sh` script.
```

2018-12-10 10:38 UTC, klaudiagrz commented on tools/stress-etcd/README.md
> +It creates a subdirectory `ssl` that contains 3 files:
```suggestion
It creates the `ssl` subdirectory that contains `etcd-client.crt`, `etcd-client.key`, and `etcd-client-ca.crt` files. 
```

2018-12-10 10:38 UTC, klaudiagrz commented on tools/stress-etcd/README.md
> +etcd-client.crt, etcd-client.key, etcd-client-ca.crt.
Please remove this line and move this paragraph under the point no.2.

2018-12-10 10:38 UTC, klaudiagrz commented on tools/stress-etcd/README.md
> +1. Establish a connection to the etcd cluster
```suggestion
1. Establish a connection to the etcd cluster.
```

2018-12-10 10:38 UTC, klaudiagrz commented on tools/stress-etcd/README.md
> +2. Download certificates using `get-ssl-files.sh`
```suggestion
2. Download certificates using the `get-ssl-files.sh` script.
```

2018-12-10 10:38 UTC, klaudiagrz commented on tools/stress-etcd/README.md
> +3. Run the `run-test.sh` script
```suggestion
3. Run the `run-test.sh` script.
```

2018-12-10 10:38 UTC, klaudiagrz commented on tools/stress-etcd/README.md
> +Executing the `run-test.sh` triggers the test with default settings.
```suggestion
Run `run-test.sh` to trigger the test with default settings. 
```

2018-12-10 10:38 UTC, klaudiagrz commented on tools/stress-etcd/README.md
> +It spawns the container, mounts the ssl directory and supplies following parameters:
```suggestion
It spawns the container, mounts the `ssl` directory, and provides the following parameters:
```

2018-12-10 10:38 UTC, klaudiagrz commented on tools/stress-etcd/README.md
> +* ETCD_SERVER - the address of the server (default: host.docker.internal:2379)
```suggestion
* **ETCD_SERVER**, which is the address of the server (default: `host.docker.internal:2379`).
```

2018-12-10 10:38 UTC, klaudiagrz commented on tools/stress-etcd/README.md
> +* KEY_COUNT - number of keys to populate (default: 100)
```suggestion
* **KEY_COUNT**, which is the number of keys to populate (default: `100`).
```

2018-12-10 10:38 UTC, klaudiagrz commented on tools/stress-etcd/README.md
> +* KEY_SIZE - size of each key in bytes (default: 1000)
```suggestion
* **KEY_SIZE**, which is the size of each key in bytes (default: `1000`).
```

2018-12-10 10:38 UTC, klaudiagrz commented on tools/stress-etcd/README.md
> +## Examples
```suggestion
### Examples
```

2018-12-10 10:38 UTC, klaudiagrz commented on tools/stress-etcd/README.md
> +During execution of the test you can see the following information:
```suggestion
The following information appears when you run the test:
```

2018-12-10 10:38 UTC, klaudiagrz commented on tools/stress-etcd/README.md
> +In case you want to test multiple workers in the same time you
```suggestion
If you want to test multiple workers at the same time, 
```

2018-12-10 10:38 UTC, klaudiagrz commented on tools/stress-etcd/README.md
> +have to spin up several instances of the `run-test.sh` script.
```suggestion
spin up several instances of the `run-test.sh` script.
```

2018-12-10 10:38 UTC, klaudiagrz commented on tools/stress-etcd/README.md
> +During execution you can observe load on the etcd cluster:
```suggestion
When running the test, you can observe the load on the etcd cluster:
```

2018-12-10 10:38 UTC, klaudiagrz commented on tools/stress-etcd/README.md
> +The graphs show load on a cluster in the following configuration:
```suggestion
The graphs show the load on the cluster in the following configuration:
```

2018-12-10 10:38 UTC, klaudiagrz commented on tools/stress-etcd/README.md
> +## Building
As discussed, please make it the 1st point on the list.

`1. Build a Docker image`

2018-12-10 10:38 UTC, klaudiagrz commented on tools/stress-etcd/README.md
> +Execute script `build.sh`, it creates a new docker image named "stress-etcd"
```suggestion
Run the `build.sh` script to create a new Docker image named `stress-etcd`.
```

2018-12-10 10:38 UTC, klaudiagrz commented on tools/stress-etcd/README.md
> +![](docs/assets/example-test-results.png)
I would be more than happy to see the gray, 1pt border around the screenshot.

2018-12-10 13:28 UTC, klaudiagrz commented on tools/stress-etcd/README.md
> +Pods name changed from "core-catalog-etcd-stateful-X" to "service-catalog-etcd-stateful-X". If you need
```suggestion
Pods name changed from `core-catalog-etcd-stateful-X` to `service-catalog-etcd-stateful-X`. If you need
```

2018-12-10 13:28 UTC, klaudiagrz commented on tools/stress-etcd/README.md
> +- 3 etcd nodes, ram=512MB, snapshot-count=10000
```suggestion
- three etcd Nodes, ram=512MB, snapshot-count=10000
```

2018-12-10 13:28 UTC, klaudiagrz commented on tools/stress-etcd/README.md
> +- 2 stress-etcd workers, key_size=2000
```suggestion
- two stress-etcd workers, key_size=2000
```

2018-12-10 13:36 UTC, klaudiagrz approved these changes

2018-12-11 11:56 UTC, mszostok requested changes

2018-12-11 11:56 UTC, mszostok commented on tools/stress-etcd/README.md
> +# Stress-etcd
we should add the `prerequisite` section (require docker, kubectl etc)

IMO is worth to mention that this script will work currently only on MacOS system (host.docker.internal)

2018-12-11 11:56 UTC, mszostok commented on tools/stress-etcd/README.md
> +If you want to test multiple workers at the same time,
IMO "spin up" can be a little bit misleading, we can spin cluster or sth like that, but here imo more accurate will be sth 
"spin up several instances of the `run-test.sh` script." -> "execute the `run-test.sh` script in multiple shells."

2018-12-11 11:56 UTC, mszostok commented on tools/stress-etcd/assets/stress.sh
> +sleep 2
why we need that sleep?

2018-12-11 11:56 UTC, mszostok commented on tools/stress-etcd/assets/stress.sh
> +#!/bin/bash
_General comment_
For now, IMO it's a little bit messy. Where the scripts should be? On root or in assets folder?

Now, you have scripts on root 
- build.sh
- get-ssl-files.sh
- run-test.sh 
and in assets/stress.sh

IMO only `build.sh` can be on root but `run-test.sh`, `get-ssl-files.sh` and `stress.sh` should be e.g. in **cmd** folder (imo **assets** name can be missleading)

Additionally the `build.sh` script is so simple that I wonder if it could be just inlined in the documentation:
Instead of:
> 1. Run the `build.sh` script to create a new Docker image named `stress-etcd`.

add sth like:
> 1. Build the Docker image by running this command:
> `docker build -t stress-etcd .`

2018-12-13 11:37 UTC, adamwalach commented on tools/stress-etcd/assets/stress.sh
> +sleep 2
It was there to keep the version of etcd on the screen for a bit longer. Not really needed. I removed it.

2018-12-13 11:38 UTC, adamwalach commented on tools/stress-etcd/assets/stress.sh
> +#!/bin/bash
* removed build.sh
* stress.sh is now in the main directory
* get-ssl-files.sh and run-tests.sh were moved to cmd subdirectory
* updated docs

2018-12-13 11:39 UTC, adamwalach commented on tools/stress-etcd/README.md
> +# Stress-etcd
fixed

2018-12-13 11:39 UTC, adamwalach commented on tools/stress-etcd/README.md
> +If you want to test multiple workers at the same time,
fixed

2018-12-13 21:01 UTC, mszostok approved these changes

2018-12-13 21:23 UTC, merged